[phases.setup]
nixpkgs = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.11.tar.gz"
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"