name = "neurobotanica-api"
main = "workers/entry.js"
compatibility_date = "2024-01-19"

[env.production]
# Production environment settings

[env.production.vars]
# Environment variables

[[env.production.d1_databases]]
binding = "DB"
database_name = "neurobotanica"
database_id = "a2818297-ae0e-4514-bc1c-5dc2bb8599fc"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "586ffb1e74594be1bfa58f34b80158dd"
preview_id = "586ffb1e74594be1bfa58f34b80158dd"